version: '3.4'
services:
  administrator:
    build:
      context: ./
      dockerfile: docker/administrator/Dockerfile
    network_mode: host
    tty: true
    stdin_open: true
    entrypoint:
      - /bin/bash
    volumes:
      - ./users:/users
